from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/auth/", include("djoser.urls")),
    path("api/auth/", include("djoser.urls.jwt")),
    path("api/", include("store.urls")),

    # --- API DOCUMENTATION URLS (using drf-spectacular) ---
    # Serves the autogenerated schema file (e.g., for machine consumption)
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),

    # Serves the interactive Swagger UI. This is the main link you will use.
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

    # Optional: Serves an alternative documentation UI (ReDoc)
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

# Conditionally add the debug toolbar URL when in development
if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

