# Generated by Django 5.2.6 on 2025-10-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_remove_product_colors_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
